### ISSUE TITLE
Championship table - truncate rule

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#173]
When the table is displayed from team "commandos" :

![img1](https://user-images.githubusercontent.com/95641846/145696229-8b6c1ff0-52af-41ff-9198-33c5c29f2963.jpg)

When table displayed from team "tournez Nadège" :

![img2](https://user-images.githubusercontent.com/95641846/145696245-a9cbc3ad-a0cd-4f25-b179-5db08da99837.jpg)

It seems the truncate rule is extended when the difference of points is displayed.

**Comment by eric-taix** [comment]
Well done. It should be the same rule: if the name of the team is too long then truncate it.

I think I'll use fade instead of ellipsis to truncate because ellipsis rule use only word break (space, hyphen, ...) while fade rule can truncate everywhere in a word.

I'll probably also remove the point difference between the current team and others in parenthesis as it's not very useful, it takes some space and it's confusing with the difference of match number. WDYT?

**Comment by Matt-VCV** [comment]
Yes for the fade rule.
And good one for the Diff point, I think we can do the maths ^^
