### ISSUE TITLE
How to send result to volley34

### ISSUE THREAD

**Issue by eric-taix** [eric-taix/volley34-mobile#189]
When I'll implement the scoreboard (or a manual score form depending on the due date), how do I have to send the result?

Is it a POST http request?
If yes what are the fields to use?
What is the URL?

Also is there a way to test sending result without disturbing people or the system?

**Comment by Lo0ping** [comment]
Volley 34 api is not secured with auth method or token, so there is no post method allowed.

**Comment by eric-taix** [comment]
I understand. How can I send a match result? I know that results can be sent by email but I would like to hide it from the user, so is there another way that I can use as you currently do in the Web site (Can I use it)?

For future release of this application (V2) do you think that it will be possible to secure some API endpoints to send delayed matches or match results?

**Comment by eric-taix** [comment]
When I wrote `Is it a POST http request` I would like to ask if I can use the current HTTP form currently used in the web site:   

```. 
<form name="aspnetForm" method="post" action="./SaisieResultat.aspx" id="aspnetForm" enctype="multipart/form-data">
...
<input name="ctl00$ctl00$cphDefault$cphCompetition$tbNom" type="text" id="ctl00_ctl00_cphDefault_cphCompetition_tbNom" tabindex="1" style="width:90%;">
<input name="ctl00$ctl00$cphDefault$cphCompetition$tbEmail" type="text" id="ctl00_ctl00_cphDefault_cphCompetition_tbEmail" tabindex="2" style="width:90%;">
<select name="ctl00$ctl00$cphDefault$cphCompetition$ddlEquipe" onchange="javascript:setTimeout('__doPostBack(\'ctl00$ctl00$cphDefault$cphCompetition$ddlEquipe\',\'\')', 0)" id="ctl00_ctl00_cphDefault_cphCompetition_ddlEquipe" tabindex="3" style="width:300px;">
  ...
</select>
<select name="ctl00$ctl00$cphDefault$cphCompetition$ddlMatch" onchange="javascript:setTimeout('__doPostBack(\'ctl00$ctl00$cphDefault$cphCompetition$ddlMatch\',\'\')', 0)" id="ctl00_ctl00_cphDefault_cphCompetition_ddlMatch" tabindex="4" class="DropDownList">
...
</select>

// and others input fields (host/visitor sets, total sets, total points, match sheet, ...)
</form>
```

**Comment by eric-taix** [comment]
Until we find a better solution, I can send an email. @Lo0ping can you provide me what do you expect in this email and the email address (something like result@volley34.fr no?)

**Comment by Lo0ping** [comment]
Result mail must be sent at resultat@volley34.fr

Sample mails :
- For Resuilt
![image](https://user-images.githubusercontent.com/3205330/146563543-511332fe-d8e4-4582-83d0-d2af7bb9ca49.png)

- For report

![image](https://user-images.githubusercontent.com/3205330/146563297-18651342-adab-449c-b874-7ed2819cc935.png)

**Comment by eric-taix** [comment]
👍 perfect.
I saw an XML file as attachment in the result email. Do you care about this file or use it internally? If yes, could you give its schema,?

**Comment by eric-taix** [comment]
Also @Lo0ping do you want the application to require a picture of the official scoresheet before being able to send the result? It can be optional as today on the web site or mandatory, as you like?

**Comment by eric-taix** [comment]
Unfortunately HTML tags are discarded by Gmail (`<b>` and `<hr>` tags) but nothing I can solve. It should be better with the iOS mailer which should not discard HTML tags.

Notes: 
- The result email is not sent automatically: the mobile application launches the mailer with a pre-build email (see the screenshot). Then the user can modify it (or not), save it as draft, discard it, or send it. BTW I have no way to know if the email has been really sent or not
- Until the production release, the recipient will be the same as the sender to avoid sending email to `resultat@volley34.fr`
- The attached image, in the screenshot below, is a fake image generated by my Android emulator to emulate a photo taken by the camera

**This is not a perfect solution, but this is a cost effective solution which should be enough for a first release as it allows the user to send the result immediately after the end of the match**

![Screenshot_1639818752](https://user-images.githubusercontent.com/712517/146635980-62ab0a0d-925d-4c7f-9776-ea6c385b4179.png)

@Lo0ping can you answer these questions so I can push my code for test? 
1- https://github.com/eric-taix/volley34-mobile/issues/189#issuecomment-996808178
2- https://github.com/eric-taix/volley34-mobile/issues/189#issuecomment-996820518

**Comment by matt-aubert** [comment]
**2 remarks :** 

**1. mask on result**
As discussed, a regexp could be considered in v2 for improvement.
One thing that can be done in this version is to block typing more than 2 digits per set.

**2. adding the picture :** 
This is a "nice to have" comment, that can be improved in v2 or none, just to share.
Instead of having 3 icons to choose "gallery", "take a picture" and "cancel", the frame could contain a big "+" and let the user click inside the frame and then a proposition between "gallery" or "camera".
Once the picture is added, a cross at right top corner of the frame let you delete the pic if necessary.
The same way works a profile picture in social networks.

**Comment by eric-taix** [comment]
Already implemented remark #1: the regex only allows digit and 2 digits maximum

Remark #2: I don't see the difference.
With your proposition, the user will need to click twice to take a new picture instead of 1 click (same for the gallery). And the clear button it's just a matter of position (inside or outside the picture) no?

**Comment by matt-aubert** [comment]
> Remark 2: I don't see the difference.
> With your proposition, the user will need to click twice to take a new picture instead of 1 click (same for the gallery). And the clear button it's just a matter of position (inside or outside the picture) no?_

That's a difficult point to explain, as you're right, on the "functional point of view" it makes more clicks (when using the take picture option)
However, by looking around in several apps (FB, twitter, insta ...), here is what I noticed : 
- Anytime the user is asked to upload something (picture profile or photo) it is first "one single" button then it displays "your gallery" with an additional button to "take a picture".
I think the reason is making the interface with less buttons (3 here), only 1clickable frame in my example.
So my point is more about proposing something that is matching 80% of users habits (even though it can make 1 more click if user choose "take picture").
So from my end user eyes, it makes the screen more "contemporary/modern" since it's using all major apps codes.

I add some examples below : 

![upload1](https://user-images.githubusercontent.com/95641846/147219840-bb400611-8898-49f5-b906-7719e72e0698.jpg)

![upload2](https://user-images.githubusercontent.com/95641846/147219886-3dd82d0b-0b23-4406-b754-884fc8e2b28a.jpg)

![upload3](https://user-images.githubusercontent.com/95641846/147219925-b0c2e436-4575-4c9e-967b-be0476148f91.jpg)

Do you get my point ? 😅

**Comment by eric-taix** [comment]
Yes I got it 😉
Displaying the cross icon to clear the picture inside the picture itself is quite easy.
But only one button to grab from the gallery or take the picture may be more difficult as I'm using a library which (as far as I know) don't provide this feature. I'll try!

**Comment by matt-aubert** [comment]
> Yes I got it 😉 Displaying the cross icon to clear the picture inside the picture itself is quite easy. But only one button to grab from the gallery or take the picture may be more difficult as I'm using a library which (as far as I know) don't provide this feature. I'll try!

Yes I can imagine... so no emergency at all ... I just wanted to share my feeling about that.
This can be pushed to v2 or v3 if relevant to the community
