### ISSUE TITLE
Game postponement icon

### ISSUE THREAD

**Issue by matt-aubert** [eric-taix/volley34-mobile#211]
Just my quick feeling on that: 

Currently the icon used is a icon "timer" type
It'd have a better understanding to me if this "calendar" icon type would be displayed : 

![logo-report](https://user-images.githubusercontent.com/95641846/146940005-afe588f7-0aef-4ccf-ae71-a1ea0e1aa9a1.png)

Calendar + clock

**Comment by eric-taix** [comment]
Instead of the "R" I used? Yes why not. Do you think that we should use the same icon for postponed matches and the icon used to postpone a match? I will be perhaps more simple for users to understand that "postponed" and "to postpone" are related?

**Comment by matt-aubert** [comment]
> Instead of the "R" I used? Yes why not. Do you think that we should use the same icon for postponed matches and the icon used to postpone a match? I will be perhaps more simple for users to understand that "postponed" and "to postpone" are related?

Nice thinking, initially I was just talking about the icon "to postpone" (in the circular menu) but indeed, using the same to indicate "postponed game" should make it more understandable (I guess)

**Comment by eric-taix** [comment]
Now we have to find the proper icon. Preference goes for black & white icon and SVG

**Comment by eric-taix** [comment]
Here are some icons extracted from https://svgrepo.com which is my favorite web site to grab free vectorial icons:
1- https://www.svgrepo.com/show/48300/calendar
2- https://www.svgrepo.com/svg/48579/calendar
3- https://www.svgrepo.com/svg/56251/calendar
4- https://www.svgrepo.com/svg/68117/calendar
5- https://www.svgrepo.com/svg/89992/calendar
6- https://www.svgrepo.com/svg/82160/calendar

My preference goes for 5 and 3 (in that order)

**Comment by eric-taix** [comment]
The problem is that this kind of icons are too complicated and less easy to understand. I prefer the original one with a single timer. 
![Screenshot_1640102198](https://user-images.githubusercontent.com/712517/146960146-f562ff22-fdb2-4d63-94b0-e2f7d2a7d3d7.png)
and original one
![Screenshot_1640102330](https://user-images.githubusercontent.com/712517/146960492-e7e32489-a269-4da0-906c-f426a08262a3.png)

**Comment by eric-taix** [comment]
I just use the original icon as the postponed badge in next events and agenda. Let's see if it's ok or not.

**Comment by matt-aubert** [comment]
OK, I must say anyways that, to me, this timer does not make me feel about pushing a date in the future.
More like a tool to "time" a game or something like this.

This one is quite simple though :

![image](https://user-images.githubusercontent.com/95641846/146969872-67b002e6-a75e-40bb-baaf-b9c7c3ab4bd3.png)

Maybe for this one we can propose 3 icons to the beta users group and see ?

**Comment by eric-taix** [comment]
Yes we can of course but we must show them at the size they will be displayed which can change their opinion

**Comment by matt-aubert** [comment]
Alight, I'll prepare some visual and ask

**Comment by matt-aubert** [comment]
So to come back on that topic, icon n°2 had a majority in the user group : 

https://www.svgrepo.com/svg/68117/calendar

If you don't like it, perhaps at least just a basic calendar, but a "timer" in a sport's app, will definitely send the wrong message.

![image](https://user-images.githubusercontent.com/95641846/148237732-5a466552-c0af-4b62-8047-65cbe6f4355d.png)

**Comment by eric-taix** [comment]
@matt-aubert Sorry I have to use another one (but similar), because the selected icon has very thin lines which looks very strange compared to other icons (I suppose you modified it with an image editor in https://github.com/eric-taix/volley34-mobile/issues/211#issuecomment-1005762744).

WDYT? (my preference goes to the first one)
<img width="308" alt="Capture d’écran 2022-01-05 à 21 20 26" src="https://user-images.githubusercontent.com/712517/148283722-bf406cee-47eb-466a-a387-3681aae9d432.png">

<img width="314" alt="Capture d’écran 2022-01-05 à 21 10 33" src="https://user-images.githubusercontent.com/712517/148282811-46c76d07-6fe9-486f-8010-127e34c57c05.png">

**Comment by matt-aubert** [comment]
Yes first one is less complex 👍🏻
