### ISSUE TITLE
Filter informations disappear when layout is landscape

### ISSUE THREAD

**Issue by clapoujade** [eric-taix/volley34-mobile#239]
![IMG_20220106_103412](https://user-images.githubusercontent.com/95589274/148361867-b83f9043-8319-42bf-a3eb-199b5f99102b.jpg)
When 'championnat' page is displayed and when a filter is used...all information related to the filter just disappear when layout is landscape
In the above screenshot, the filter is against a searchstring 'vcv'

**Comment by matt-aubert** [comment]
I have that too. Even if you don't use filter : in landscape, the filtering and search tool is not accessible.

@eric-taix : is it meant to be like this ?

I also noticed that the teams of research : VCV (in this case) are not in "bold" anymore when switching to landscape.
But the effect of the filter remained.

**Comment by eric-taix** [comment]
This is related to [#229](https://github.com/eric-taix/volley34-mobile/discussions/229#discussion-3776571).
In few days the landscape will be the same page as the portrait (which is not the case currently that's why filters and search keywords are missing when switching to landscape). According to the orientation, I'll display some details or not.
