### ISSUE TITLE
[dashboard] calendar content 

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#39]
Current calendar does not contain all events but just some VCV samples

**Comment by thomasFoulon** [comment]
I noticed that there is no future event returned by the API. Is there a way to test that the functionality works well without future events ?

**Comment by Lo0ping** [comment]
> I noticed that there is no future event returned by the API. Is there a way to test that the functionality works well without future events ?

Yes, I will change  events date to give you test case

**Comment by thomasFoulon** [comment]
Thanks !

**Comment by thomasFoulon** [comment]
Hi! I'm looking for a way to get all coming matches for a team or a club possibly with date constraints. I see that there is an option `matchs=true` on the `calendars` part of the API but when I put this option all the matches of each team are returned even with the option `club={{club}}`. On the other hand the part `matchs` of the API doesn't have any team, club or date option.

It would be very nice to add options on the part `matchs` of the API because it returns `Matchs` objects which are what I need in the application for these types of event. Using the `calendars` part of the API is also possible but the code of the match in the `CalendarEvent` would be nice if it's possible.

**Comment by thomasFoulon** [comment]
Anyway, I saw you haven't changed events date yet ! Could you do it ?
