### ISSUE TITLE
Don't display data "Code" in Page

### ISSUE THREAD

**Issue by Lo0ping** [eric-taix/volley34-mobile#85]
Team Code is an internal Auto generated ID which have no sense for users. 
Please, Only display Team Name in pages

Club Code is not a known data for users. 
Please, replace it by SigleClub Value

Globally, only CalendarEventId and MatchCode could be displayed, not other data codes

**Comment by thomasFoulon** [comment]
I agree but I don't have enough space to display the full team name. How can I do ?

**Comment by Lo0ping** [comment]
> I agree but I don't have enough space to display the full team name. How can I do ?

I know this problem, some name are too long
Perhaps, you can use : 
- adaptative font size 
- word wrap
- ellipsis

**Comment by eric-taix-teads** [comment]
Adaptive font size is not a good idea as it can be too small ! 
If the text to display is important (like team's name) then word wrap is the best option. If the text is not very important (like the address of an event in the agenda) then ellipsis is a good option.

FYI: I'm already fixing the team's page and display the team's name instead of the team's code (in the title) and display the club's name instead of ... (in the subtitle) + other improvements.

**Comment by eric-taix-teads** [comment]
Fixed by #98
